version: '3.9'

services:
  app:
    container_name: api
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=ttek_dev_db
      - DB_USER=ttek_user
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ttek_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: ttek_dev_db
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data: