# Generated by Django 3.2.23 on 2023-12-29 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(default=datetime.datetime(2023, 12, 29, 16, 48, 4, 868329, tzinfo=utc), max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
