# Generated by Django 3.2.23 on 2023-12-03 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('other_names', models.CharField(blank=True, default='', max_length=32)),
                ('gender', models.CharField(max_length=8)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=32)),
                ('home_town', models.CharField(max_length=32)),
                ('home_district', models.CharField(max_length=32)),
                ('home_region', models.CharField(max_length=32)),
                ('nationality', models.CharField(max_length=32)),
                ('religion', models.CharField(blank=True, default='', max_length=32)),
                ('disability', models.BooleanField(default=False)),
                ('disability_description', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('residential_address', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staffs', related_query_name='staff_list', to='core.school')),
            ],
        ),
    ]
