# Generated by Django 3.2.23 on 2023-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='staff',
            name='home_district',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='home_region',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='home_town',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nationality',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='other_names',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='place_of_birth',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
