# Generated by Django 3.2.23 on 2023-12-29 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_user_account_id'),
        ('staff', '0004_auto_20231210_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='digital_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='staff',
            name='national_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='permanent_address',
            field=models.CharField(default='Permanent address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='postal_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Professional', 'Professional')], max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Non Teaching', 'Non Teaching')], max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='religion',
            field=models.CharField(blank=True, choices=[('African Traditional Religion', 'African Traditional Religion'), ('Christian', 'Christian'), ('Islam', 'Islam'), ('Rastafarianism', 'Rastafarianism'), ('Judaism', 'Judaism'), ('Hinduism', 'Hinduism'), ('Other', 'Other')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personal_details', to='core.school'),
        ),
    ]
