# Generated by Django 3.2.23 on 2024-01-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email'),
        ('staff', '0006_auto_20231230_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_list', to='core.school'),
        ),
    ]
